#define ICO_NEW                          0
#define ICO_OPEN                         1
#define ICO_SAVE                         2
#define ICO_PRINT                        3
#define ICO_CUT                          4
#define ICO_COPY                         5
#define ICO_PASTE                        6
#define ICO_CLEAR                        7
#define ICO_UNDO                         8
#define ICO_REDO                         9
#define ICO_FIND                         10
#define ICO_REPLACE                      11
#define ICO_CLOSE                        12
#define ICO_MACROPLAY                    13
#define ICO_MACROSTOPRECORD              14
#define ICO_MACRORECORD                  15
#define ICO_GO                           16
#define ICO_BUILD                        17
#define ICO_COMPILE                      18
#define ICO_VIEWEOL                      19
#define ICO_SAVEAS                       20
#define ICO_MONOFONT                     21
#define ICO_READONLY                     22
#define ICO_TOGGLEOUTPUT                 23
#define ICO_FULLSCREEN                   24
#define ICO_HELP                         25
#define ICO_OPENGLOBALPROPERTIES         26
#define ICO_OPENUSERPROPERTIES           27
#define ICO_OPENABBREVPROPERTIES         28
#define ICO_WRAP                         29
#define ICO_SAVEALL                      30
#define ICO_CLOSEALL                     31
#define ICO_PRINTSETUP                   32
#define ICO_SESSION_MANAGER              33
#define ICO_LOADSESSION                  34
#define ICO_SAVESESSION                  35
#define ICO_SELECTALL                    36
#define ICO_SELECTTOBRACE                37
#define ICO_FINDNEXT                     38
#define ICO_FINDNEXTBACK                 39
#define ICO_FINDINFILES                  40
#define ICO_GOTO                         41
#define ICO_BOOKMARK_NEXT                42
#define ICO_BOOKMARK_PREV                43
#define ICO_BOOKMARK_TOGGLE              44
#define ICO_BOOKMARK_CLEARALL            45
#define ICO_LINENUMBERMARGIN             46
#define ICO_ONTOP                        47
#define ICO_LIST_OF_FUNCTIONS_PROCEDURES 48
#define ICO_SPELLING                     49
#define ICO_CHOICE_COLOR_FROM_A_PALETTE  50
#define ICO_SIDEBAR                      51
#define ICO_REPLACE_SPACES               52
#define ICO_CHANGE_CODEPAGE_RU           53
#define ICO_OPENAPIFILE                  54
#define ICO_OPEN_FAVORITE_FILES          55
#define ICO_TRIM_TRAL_SPACES             56
#define ICO_FAVORITE_FOLDERS             57
#define ICO_VIEWSPACE                    58
#define ICO_STOPEXECUTE                  59
#define ICO_HIGHLIGHTIDENTICAL           60
#define ICO_HIGHLIGHT                    61
#define ICO_FIND_AND_HIGHLIGHT           62
#define ICO_ASTYLE                       63
#define ICO_TIDY                         64
