#ifndef _YAWL_H
#include "yawl/vc6.h"
#include "yawl/twl.h"
#include "yawl/twl_data.h"
#include "yawl/twl_cntrls.h"
#include "yawl/twl_layout.h"
#include "yawl/twl_ini.h"
#include "yawl/twl_menu.h"
#include "yawl/twl_dialogs.h"
#include "yawl/twl_modal.h"
#include "yawl/twl_toolbar.h"
#include "yawl/twl_splitter.h"
#include "yawl/twl_listview.h"
#include "yawl/twl_tab.h"
#include "yawl/twl_treeview.h"
#endif
